spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crm_dev

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""

logging:
  level:
    com.becommerce.crm: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

app:
  security:
    reset-token:
      expiration-hours: 1
